version: "3.9"

services:
  projects_api:
    image: projects_api:${TAG-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db_dev

  db_dev:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devdb
    ports:
      - 5432:5432
    volumes: 
      - pgdata_dev:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  db_test:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - 5433:5432
    volumes: 
      - pgdata_test:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata_dev:
  pgdata_test:
