version: "3.9"

services:
  projects_api:
    image: projects_api:${TAG-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=defaultdb
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: